### ISSUE TITLE
Trojan detected in latest binaries

### ISSUE THREAD

**Issue by gsly** [tizbac/proxmoxbackupclient_go#12]
Downloaded the latest version and Windows Defender found Trojan:Win32/Wacatac.B!ml in both executables.

**Comment by tizbac** [comment]
Hi, very likely false positive which already happened with other golang
binaries , will check with clamav to make sure and see how to fix it

Il lun 1 gen 2024, 13:15 gsly ***@***.***> ha scritto:

**Comment by tizbac** [comment]
Have reported it to microsoft, 
https://www.virustotal.com/gui/file/25a097bd743a59d7c7f8968408cc18c4b726e30afb41c8054a0555c47a600272/detection
All detections are by Machine Learning / AI antivirus, may be the fact this program is reading files and sending them massively to pbs server and plus interacting with VSS triggering it

**Comment by Tacioandrade** [comment]
I believe that one of the reasons it is also being detected is because it uses VSS, creating and deleting snapshots.
This really is something that can be seen as something risky and generating this false positive.

**Comment by tizbac** [comment]
As of now, i see it is no longer detected as virus by defender on virustotal
