### ISSUE TITLE
Unable to download previous backuped files

### ISSUE THREAD

**Issue by svendoering** [tizbac/proxmoxbackupclient_go#16]
After upload files to the PBS. I can not download/restore the files from the PBS
Tested on a Windows 10 and Windows 11 and Windows Server 2019 with BackupServer 3.1-2 and 3.1-4
Compiled with TDM-GCC-64

Upload:
![image](https://github.com/tizbac/proxmoxbackupclient_go/assets/58389412/75514edd-89ac-470a-bdda-583843333850)

Restore:
![image](https://github.com/tizbac/proxmoxbackupclient_go/assets/58389412/b3ecab56-f05d-46b1-a36d-348589579954)

It is possible to download the index.json and the catalog.pcat1.didx (binary) 
It is NOT possible to download the backup.pxar.didx.

This is the index.json
{
  "backup-id": "praxisserver",
  "backup-time": 1707237665,
  "backup-type": "host",
  "files": [
    {
      "crypt-mode": "none",
      "csum": "92e2d87c67a47e8e2703cb5d9ce692b4fb6363984961e7dbaa0bece10832ccb4",
      "filename": "backup.pxar.didx",
      "size": 496
    },
    {
      "crypt-mode": "none",
      "csum": "c2512a3b8bf817753870fc39a43f3d72da4d063af0ec173cf9ae2e0f6a57ec2e",
      "filename": "catalog.pcat1.didx",
      "size": 64
    }
  ],
  "signature": null,
  "unprotected": {
    "chunk_upload_stats": {
      "compressed_size": 76,
      "count": 1,
      "duplicates": 0,
      "size": 545
    }
  }
}

**Comment by svendoering** [comment]
Currently I am backup up the same systems via wsl and the unix backup client. From these backups i can download files without problems. With wsl I am missing the snapshot feature.

**Comment by svendoering** [comment]
<img width="620" alt="image" src="https://github.com/tizbac/proxmoxbackupclient_go/assets/58389412/e4e2e6f1-da14-4219-9e84-f540836c09d8">

**Comment by tizbac** [comment]
Try again with latest version ( v0.0.3 ) thanks

**Comment by svendoering** [comment]
With v0.0.3 i can download the files.

Good work and Thank you
