### ISSUE TITLE
Howto use

### ISSUE THREAD

**Issue by kmorber** [tizbac/proxmoxbackupclient_go#3]
Hello,

can you please explain the command line syntax?

BR

**Comment by jochumdev** [comment]
They are defined here: https://github.com/tizbac/proxmoxbackupclient_go/blob/master/main.go#L53C1-L60C73

Hope that helps.

**Comment by kmorber** [comment]
Thank you for your quick response, but i am not sure about:

Base URL for the PBS client

What do i have to input?

**Comment by jochumdev** [comment]
According to https://github.com/tizbac/proxmoxbackupclient_go/blob/master/pbsapi.go#L91 it seems to be something like:

https://10.167.160.14:8007

**Comment by tizbac** [comment]
It will show command line syntax if called with wrong or no arguments, and i confirm base url being what jochumdev said
