### ISSUE TITLE
Make certfingerprint parameter optional

### ISSUE THREAD

**Issue by guerrieroriccardo** [tizbac/proxmoxbackupclient_go#32]
As title, having to manually specify each time the PBS fingerprint is quite annoying, especially if the remote PBS server have a valid HTTP/S certificate.
Tried on Windows 11.

**Comment by giuseongit** [comment]
Addresses: https://github.com/tizbac/proxmoxbackupclient_go/issues/32

Basically, if you're using a valid ssl certificate, you can now skip manual verification: if you do not provide any fingerprint, the system-installed ones will be used (you can still point out the expected fingerprint for extra security), this allow to keep a smaller config file.
